### PR TITLE
Update to v1.7.0 of Terraform bridge

### PR DESCRIPTION
**Pull request by jen20**
This updates the Terraform Bridge to v1.7.0, which removes the need for vendoring dependencies. CI will tell us whether the Travis configuration needs changing also.

### CODE REVIEW

**Comment by stack72** [comment]
Looks like you are missing a go mod tidy here so the Go gets from the scripts are updating the files

**Comment by jen20** [comment]
I think there's a better way to handle this by disabling module support while installing ancillary tools (which will go away when we move away from Travis anyway).  Ideally we shouldn't be modifying the `go.mod` as part of a build and then letting `tidy` fix it.

**Comment by jen20** [comment]
I believe pulumi/scripts#97 will address this failure.

**Comment by jen20** [comment]
@stack72 this looks good now. I think we should consider pre-commit hooks for ensuring `go mod tidy` is run going forwards, but this can be done later since CI will catch it for now.

**Pull request merged**
